# Generated by Django 5.2.12 on 2026-04-07 22:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('card_kind', models.CharField(choices=[('benefit', 'Benefit'), ('credit', 'Credit')], max_length=20)),
                ('holder_name', models.CharField(max_length=120)),
                ('brand', models.CharField(max_length=40)),
                ('last_four', models.CharField(max_length=4)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('monthly_spend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('closing_day', models.PositiveSmallIntegerField(default=1)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('display_order', 'name'),
            },
        ),
    ]
